#!/bin/bash
# Environment variables for client: medcue
# Generated by ctx-creds

# AWS credentials
# export AWS_MAIN-ACCOUNT="$(keepassxc-cli show /path/to/database.kdbx 'AWS/MainAccount/AccessKey' --show-password)"

# SSH credentials
# export SSH_SERVER1="$(keepassxc-cli show /path/to/database.kdbx 'SSH/MedcueServer1' --show-password)"

