global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # MedCue Backend API
  - job_name: 'medcue-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: http

  # MedCue Frontend (if metrics endpoint exists)
  - job_name: 'medcue-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: http

  # Health checks
  - job_name: 'medcue-health-checks'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/health/detailed'
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: http

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node/System metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Alertmanager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 30s

  # HIPAA Compliance monitoring
  - job_name: 'hipaa-compliance'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/health/hipaa'
    scrape_interval: 60s
    scrape_timeout: 10s
    scheme: http

  # Security monitoring
  - job_name: 'security-health'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/health/security'
    scrape_interval: 60s
    scrape_timeout: 10s
    scheme: http